INSERT INTO setor (nome_setor) VALUES
('Tecnologia da Informação'),
('Recursos Humanos'),
('Financeiro'),
('Marketing'),
('Operações'),
('Vendas'),
('Atendimento ao Cliente'),
('Logística'),
('Produção'),
('Administrativo'),
('Jurídico'),
('Compras'),
('Qualidade'),
('Projetos'),
('Sustentabilidade');

INSERT INTO cargo (nome_cargo) VALUES
('Desenvolvedor'),
('Analista de RH'),
('Contador'),
('Especialista de Marketing'),
('Gerente de Operações'),
('Vendedor'),
('Atendente'),
('Analista de Logística'),
('Técnico de Produção'),
('Assistente Administrativo'),
('Advogado'),
('Comprador'),
('Analista de Qualidade'),
('Gerente de Projetos'),
('Coordenador de Sustentabilidade');

INSERT INTO usuario (nome, login, senha, email, setor_idSetor, cargo_idCargo) VALUES
('Alice Silva', 'alice.silva', 'senha123', 'alice.silva@example.com', 1, 5),
('Bruno Costa', 'bruno.costa', 'senha123', 'bruno.costa@example.com', 2, 3),
('Carla Pereira', 'carla.pereira', 'senha123', 'carla.pereira@example.com', 3, 8),
('Daniel Oliveira', 'daniel.oliveira', 'senha123', 'daniel.oliveira@example.com', 4, 1),
('Eduarda Santos', 'eduarda.santos', 'senha123', 'eduarda.santos@example.com', 5, 6),
('Felipe Almeida', 'felipe.almeida', 'senha123', 'felipe.almeida@example.com', 6, 2),
('Gabriela Lima', 'gabriela.lima', 'senha123', 'gabriela.lima@example.com', 7, 7),
('Henrique Martins', 'henrique.martins', 'senha123', 'henrique.martins@example.com', 8, 4),
('Isabela Rocha', 'isabela.rocha', 'senha123', 'isabela.rocha@example.com', 9, 9),
('João Mendes', 'joao.mendes', 'senha123', 'joao.mendes@example.com', 10, 10),
('Karina Ferreira', 'karina.ferreira', 'senha123', 'karina.ferreira@example.com', 11, 11),
('Lucas Nascimento', 'lucas.nascimento', 'senha123', 'lucas.nascimento@example.com', 12, 12),
('Mariana Souza', 'mariana.souza', 'senha123', 'mariana.souza@example.com', 13, 13),
('Nicolas Lima', 'nicolas.lima', 'senha123', 'nicolas.lima@example.com', 14, 14),
('Olivia Dias', 'olivia.dias', 'senha123', 'olivia.dias@example.com', 15, 15),
('Paulo Gomes', 'paulo.gomes', 'senha123', 'paulo.gomes@example.com', 16, 16),
('Quiteria Alves', 'quiteria.alves', 'senha123', 'quiteria.alves@example.com', 17, 17),
('Rafael Pires', 'rafael.pires', 'senha123', 'rafael.pires@example.com', 18, 18),
('Sofia Martins', 'sofia.martins', 'senha123', 'sofia.martins@example.com', 19, 1),
('Tiago Ribeiro', 'tiago.ribeiro', 'senha123', 'tiago.ribeiro@example.com', 20, 2),
('Ursula Santos', 'ursula.santos', 'senha123', 'ursula.santos@example.com', 21, 3),
('Vinicius Cardoso', 'vinicius.cardoso', 'senha123', 'vinicius.cardoso@example.com', 22, 4),
('Wesley Ferreira', 'wesley.ferreira', 'senha123', 'wesley.ferreira@example.com', 23, 5),
('Xuxa Lima', 'xuxa.lima', 'senha123', 'xuxa.lima@example.com', 1, 6),
('Yasmin Costa', 'yasmin.costa', 'senha123', 'yasmin.costa@example.com', 2, 7),
('Zé Carlos', 'ze.carlos', 'senha123', 'ze.carlos@example.com', 3, 8),
('Ana Beatriz', 'ana.beatriz', 'senha123', 'ana.beatriz@example.com', 4, 9),
('Bruno Henrique', 'bruno.henrique', 'senha123', 'bruno.henrique@example.com', 5, 10),
('Clara Mendes', 'clara.mendes', 'senha123', 'clara.mendes@example.com', 6, 11),
('Diego Almeida', 'diego.almeida', 'senha123', 'diego.almeida@example.com', 7, 12),
('Elena Martins', 'elena.martins', 'senha123', 'elena.martins@example.com', 8, 13);

INSERT INTO servico (tipoServico) VALUES 
("Formatação de Computador"),
("Remoção de Vírus e Malware"),
("Backup de Dados"),
("Configuração de Rede"),
("Instalação de Software"),
("Manutenção Preventiva"),
("Troca de Peças de Hardware"),
("Recuperação de Dados"),
("Atualização de Sistema Operacional"),
("Configuração de Impressoras"),
("Instalação de Antivírus"),
("Limpeza Interna de Computador"),
("Configuração de E-mail"),
("Diagnóstico de Problemas"),
("Otimização de Desempenho"),
("Troca de Tela de Notebook"),
("Reparo de Placa-mãe"),
("Instalação de Drivers"),
("Configuração de Roteador"),
("Criação de Rede Wi-Fi"),
("Instalação de Sistemas de CFTV"),
("Suporte Remoto"),
("Montagem de Computador"),
("Criação de Backup Automático"),
("Manutenção de Servidores"),
("Remoção de Acessos Não Autorizados"),
("Configuração de Servidores em Nuvem"),
("Suporte a Softwares Empresariais"),
("Reparo de Fontes de Alimentação"),
("Testes de Componentes Eletrônicos");

INSERT INTO `chamado` (`servico_idServico`, `titulo`, `descricao`, `prioridade`, 
            `status`, `dataAbertura`, `dataDechamento`, `usuario_abertura`, `usuario_atendimento`) 
VALUES
(1, 'Problema de Conexão', 'Usuário relatou problemas de conexão com a internet.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 2),
(2, 'Erro no Sistema', 'Erro ao acessar o sistema, por favor verificar.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 4),
(3, 'Solicitação de Instalação', 'Solicitação para instalação de software.', 'BAIXA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 1),
(4, 'Dúvida sobre o Sistema', 'Usuário tem dúvidas sobre o uso do sistema.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 2),
(5, 'Problema com Impressora', 'Impressora não está funcionando corretamente.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 3),
(6, 'Erro de Login', 'Usuário não consegue fazer login no sistema.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 4),
(7, 'Troca de Senha', 'Solicitação para troca de senha.', 'BAIXA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 1),
(8, 'Problema com E-mail', 'Usuário não está recebendo e-mails.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 2),
(9, 'Erro ao Gerar Relatório', 'Erro ao tentar gerar relatórios no sistema.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 3),
(10, 'Solicitação de Acesso', 'Usuário solicita acesso a um sistema específico.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 4),
(1, 'Problema com a Rede', 'Usuário relatou problemas com a rede Wi-Fi.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 1),
(2, 'Erro de Atualização', 'Erro ao tentar atualizar o sistema.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 2),
(3, 'Dúvida sobre Procedimentos', 'Usuário tem dúvidas sobre os procedimentos de trabalho.', 'BAIXA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 3),
(1, 'Problema de Conexão', 'Usuário relatou problemas de conexão com a internet.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 2),
(2, 'Erro no Sistema', 'Erro ao acessar o sistema, por favor verificar.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 4),
(3, 'Solicitação de Instalação', 'Solicitação para instalação de software.', 'BAIXA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 1),
(4, 'Dúvida sobre o Sistema', 'Usuário tem dúvidas sobre o uso do sistema.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 2),
(5, 'Problema com Impressora', 'Impressora não está funcionando corretamente.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 3),
(6, 'Erro de Login', 'Usuário não consegue fazer login no sistema.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 4),
(7, 'Troca de Senha', 'Solicitação para troca de senha.', 'BAIXA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 1),
(8, 'Problema com E-mail', 'Usuário não está recebendo e-mails.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 2),
(9, 'Erro ao Gerar Relatório', 'Erro ao tentar gerar relatórios no sistema.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 3),
(10, 'Solicitação de Acesso', 'Usuário solicita acesso a um sistema específico.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 4),
(1, 'Problema com a Rede', 'Usuário relatou problemas com a rede Wi-Fi.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 1),
(2, 'Erro de Atualização', 'Erro ao tentar atualizar o sistema.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 2),
(3, 'Dúvida sobre Procedimentos', 'Usuário tem dúvidas sobre os procedimentos de trabalho.', 'BAIXA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 3);



