INSERT INTO `chamado` (`servico_idServico`, `titulo`, `descricao`, `prioridade`, 
            `status`, `dataAbertura`, `dataDeFechamento`, `usuario_abertura`, `usuario_atendimento`) 
VALUES
(1, 'Problema de Conexão', 'Usuário relatou problemas de conexão com a internet.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 2),
(2, 'Erro no Sistema', 'Erro ao acessar o sistema, por favor verificar.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 4),
(3, 'Solicitação de Instalação', 'Solicitação para instalação de software.', 'BAIXA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 1),
(4, 'Dúvida sobre o Sistema', 'Usuário tem dúvidas sobre o uso do sistema.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 2),
(5, 'Problema com Impressora', 'Impressora não está funcionando corretamente.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 3),
(6, 'Erro de Login', 'Usuário não consegue fazer login no sistema.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 4),
(7, 'Troca de Senha', 'Solicitação para troca de senha.', 'BAIXA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 1),
(8, 'Problema com E-mail', 'Usuário não está recebendo e-mails.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 2),
(9, 'Erro ao Gerar Relatório', 'Erro ao tentar gerar relatórios no sistema.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 3),
(10, 'Solicitação de Acesso', 'Usuário solicita acesso a um sistema específico.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 4),
(1, 'Problema com a Rede', 'Usuário relatou problemas com a rede Wi-Fi.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 1),
(2, 'Erro de Atualização', 'Erro ao tentar atualizar o sistema.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 2),
(3, 'Dúvida sobre Procedimentos', 'Usuário tem dúvidas sobre os procedimentos de trabalho.', 'BAIXA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 3),
(1, 'Problema de Conexão', 'Usuário relatou problemas de conexão com a internet.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 2),
(2, 'Erro no Sistema', 'Erro ao acessar o sistema, por favor verificar.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 4),
(3, 'Solicitação de Instalação', 'Solicitação para instalação de software.', 'BAIXA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 1),
(4, 'Dúvida sobre o Sistema', 'Usuário tem dúvidas sobre o uso do sistema.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 2),
(5, 'Problema com Impressora', 'Impressora não está funcionando corretamente.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 3),
(6, 'Erro de Login', 'Usuário não consegue fazer login no sistema.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 4),
(7, 'Troca de Senha', 'Solicitação para troca de senha.', 'BAIXA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 1),
(8, 'Problema com E-mail', 'Usuário não está recebendo e-mails.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 2),
(9, 'Erro ao Gerar Relatório', 'Erro ao tentar gerar relatórios no sistema.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 3),
(10, 'Solicitação de Acesso', 'Usuário solicita acesso a um sistema específico.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 4),
(1, 'Problema com a Rede', 'Usuário relatou problemas com a rede Wi-Fi.', 'ALTA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 1),
(2, 'Erro de Atualização', 'Erro ao tentar atualizar o sistema.', 'MÉDIA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 2),
(3, 'Dúvida sobre Procedimentos', 'Usuário tem dúvidas sobre os procedimentos de trabalho.', 'BAIXA', 
            'ABERTO', '2023-10-01', NULL, 
            (SELECT idUsuario FROM usuario WHERE cargo_idCargo = 1 ORDER BY RAND() LIMIT 1), 3)